src/BB.SmsQuiz.Web/Controllers/AuthenticationController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AuthenticationController.cs" company="contentedcoder.com">
//   contentedcoder.com
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using BB.SmsQuiz.Web.Infrastructure;
using BB.SmsQuiz.Web.Models;

namespace BB.SmsQuiz.Web.Controllers
{
    /// <summary>
    /// The authentication controller.
    /// </summary>
    public class AuthenticationController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationController"/> class.
        /// </summary>
        /// <param name="context">
        /// The context.
        /// </param>
        public AuthenticationController(IBaseContext context) : base(context)
        {
        }

        // GET: /Accounts/Logon
        /// <summary>
        /// The index.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        // POST: /Accounts/Logon
        /// <summary>
        /// The index.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        public ActionResult Index(AuthenticationViewModel model)
        {
            var result = Client.PostAsJsonAsync("authentication", model).Result;

            if (result.StatusCode == HttpStatusCode.OK)
            {
                FormsAuthentication.SetAuthenticationToken(result.Content.ReadAsAsync<string>().Result);
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // GET: /Accounts/LogOut
        /// <summary>
        /// The log out.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

src/BB.SmsQuiz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>@ViewBag.Title - Sms Quiz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/content/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/content/css/bootstrap-responsive.css" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

    <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                </a><a class="brand" href="/">SMS Quiz</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Competitions", "Index", "Competitions")</li>
                        <li>@Html.ActionLink("Users", "Index", "Users")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Authentication")</li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="container">
        @if (!Html.ViewData.ModelState.IsValid)
        {
            <div class="alert alert-error">
                <strong>Errors!</strong><br/>
                @foreach (var modelError in ViewData.ModelState.SelectMany(keyValuePair => keyValuePair.Value.Errors))
                {
                    @modelError.ErrorMessage<br/>
                }
            </div>
        }
        @RenderBody()
    </div>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/Content/js/bootstrap.min.js" type="text/javascript"></script>
</body>
</html>